@ClientApp_HostAddress = https://localhost:7291

GET https://localhost:7291/api/hotel/GetHotel?idHotel=1


GET {{ClientApp_HostAddress}}/room/getroombyid/{id}?idHotel=0

###

POST {{ClientApp_HostAddress}}/api/bookings/CreateBooking
Content-Type: application/json

{
  //BookingInputDto
}

###
